<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'en' => [
                    'name' => 'Food & Grocery',
                    'slug' => 'food-grocery',
                    'order_level' => 1,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Food & Grocery',
                    'meta_description' => 'Fresh Produce · Meat & Poultry · Dairy & Eggs · Snacks · Beverages',
                    'units' => ['kg', 'g', 'piece', 'pack', 'bottle', 'L'],
                    'subcategories' => [
                        'Fresh Produce',
                        'Meat & Poultry',
                        'Dairy & Eggs',
                        'Snacks',
                        'Beverages',
                    ],
                ],
                'ar' => [
                    'name' => 'المواد الغذائية والبقالة',
                    'meta_title' => 'المواد الغذائية والبقالة',
                    'meta_description' => 'خضروات وفواكه طازجة · لحوم ودواجن · ألبان وبيض · وجبات خفيفة · مشروبات',
                    'units' => ['كجم', 'جم', 'قطعة', 'عبوة', 'زجاجة', 'لتر'],
                    'subcategories' => [
                        'خضروات وفواكه طازجة',
                        'لحوم ودواجن',
                        'ألبان وبيض',
                        'وجبات خفيفة',
                        'مشروبات',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Fresh & Frozen',
                    'slug' => 'fresh-frozen',
                    'order_level' => 2,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Fresh & Frozen',
                    'meta_description' => 'Chilled Meats · Frozen Vegetables · Ready-to-Cook',
                    'units' => ['kg', 'g', 'pack', 'box'],
                    'subcategories' => [
                        'Chilled Meats',
                        'Frozen Vegetables',
                        'Ready-to-Cook',
                    ],
                ],
                'ar' => [
                    'name' => 'المنتجات الطازجة والمجمدة',
                    'meta_title' => 'المنتجات الطازجة والمجمدة',
                    'meta_description' => 'لحوم مبردة · خضروات مجمدة · وجبات جاهزة للطهي',
                    'units' => ['كجم', 'جم', 'عبوة', 'صندوق'],
                    'subcategories' => [
                        'لحوم مبردة',
                        'خضروات مجمدة',
                        'وجبات جاهزة للطهي',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Health & Beauty',
                    'slug' => 'health-beauty',
                    'order_level' => 3,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Health & Beauty',
                    'meta_description' => 'Skincare · Haircare · Cosmetics · Fragrances · Supplements',
                    'units' => ['bottle', 'tube', 'piece', 'pack', 'ml', 'g'],
                    'subcategories' => [
                        'Skincare',
                        'Haircare',
                        'Cosmetics',
                        'Fragrances',
                        'Supplements',
                    ],
                ],
                'ar' => [
                    'name' => 'الصحة والجمال',
                    'meta_title' => 'الصحة والجمال',
                    'meta_description' => 'العناية بالبشرة · العناية بالشعر · مستحضرات التجميل · العطور · مكملات غذائية',
                    'units' => ['زجاجة', 'أنبوب', 'قطعة', 'عبوة', 'مل', 'جم'],
                    'subcategories' => [
                        'العناية بالبشرة',
                        'العناية بالشعر',
                        'مستحضرات التجميل',
                        'العطور',
                        'مكملات غذائية',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Pharmacy & Medical',
                    'slug' => 'pharmacy-medical',
                    'order_level' => 4,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Pharmacy & Medical',
                    'meta_description' => 'Prescription Medicines · OTC · First Aid · Medical Devices',
                    'units' => ['box', 'strip', 'tablet', 'bottle'],
                    'subcategories' => [
                        'Prescription Medicines',
                        'OTC',
                        'First Aid',
                        'Medical Devices',
                    ],
                ],
                'ar' => [
                    'name' => 'الصيدلية والمستلزمات الطبية',
                    'meta_title' => 'الصيدلية والمستلزمات الطبية',
                    'meta_description' => 'أدوية بوصفة · أدوية بدون وصفة · إسعافات أولية · أجهزة طبية',
                    'units' => ['صندوق', 'شريط', 'قرص', 'زجاجة'],
                    'subcategories' => [
                        'أدوية بوصفة',
                        'أدوية بدون وصفة',
                        'إسعافات أولية',
                        'أجهزة طبية',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Fashion & Apparel',
                    'slug' => 'fashion-apparel',
                    'order_level' => 5,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Fashion & Apparel',
                    'meta_description' => 'Men’s Wear · Women’s Wear · Kids Wear · Footwear · Accessories',
                    'units' => ['piece', 'pair', 'set', 'box'],
                    'subcategories' => [
                        'Men’s Wear',
                        'Women’s Wear',
                        'Kids Wear',
                        'Footwear',
                        'Accessories',
                    ],
                ],
                'ar' => [
                    'name' => 'الأزياء والملابس',
                    'meta_title' => 'الأزياء والملابس',
                    'meta_description' => 'ملابس رجالية · ملابس نسائية · ملابس أطفال · أحذية · إكسسوارات',
                    'units' => ['قطعة', 'زوج', 'طقم', 'صندوق'],
                    'subcategories' => [
                        'ملابس رجالية',
                        'ملابس نسائية',
                        'ملابس أطفال',
                        'أحذية',
                        'إكسسوارات',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Sports & Outdoors',
                    'slug' => 'sports-outdoors',
                    'order_level' => 6,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Sports & Outdoors',
                    'meta_description' => 'Sportswear · Fitness Equipment · Camping Gear · Cycling',
                    'units' => ['piece', 'set', 'pair', 'kg'],
                    'subcategories' => [
                        'Sportswear',
                        'Fitness Equipment',
                        'Camping Gear',
                        'Cycling',
                    ],
                ],
                'ar' => [
                    'name' => 'الرياضة والهواء الطلق',
                    'meta_title' => 'الرياضة والهواء الطلق',
                    'meta_description' => 'ملابس رياضية · معدات لياقة · مستلزمات تخييم · دراجات',
                    'units' => ['قطعة', 'طقم', 'زوج', 'كجم'],
                    'subcategories' => [
                        'ملابس رياضية',
                        'معدات لياقة',
                        'مستلزمات تخييم',
                        'دراجات',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Electronics & Computing',
                    'slug' => 'electronics-computing',
                    'order_level' => 7,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Electronics & Computing',
                    'meta_description' => 'Mobiles · Laptops · Components · Gaming · Cameras',
                    'units' => ['piece', 'unit', 'set'],
                    'subcategories' => [
                        'Mobiles',
                        'Laptops',
                        'Components',
                        'Gaming',
                        'Cameras',
                    ],
                ],
                'ar' => [
                    'name' => 'الإلكترونيات والحاسوب',
                    'meta_title' => 'الإلكترونيات والحاسوب',
                    'meta_description' => 'هواتف محمولة · حواسيب محمولة · مكونات · ألعاب إلكترونية · كاميرات',
                    'units' => ['قطعة', 'وحدة', 'طقم'],
                    'subcategories' => [
                        'هواتف محمولة',
                        'حواسيب محمولة',
                        'مكونات',
                        'ألعاب إلكترونية',
                        'كاميرات',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Large Appliances',
                    'slug' => 'large-appliances',
                    'order_level' => 8,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Large Appliances',
                    'meta_description' => 'Refrigerators · Washing Machines · Air-Conditioners',
                    'units' => ['unit', 'piece', 'box'],
                    'subcategories' => [
                        'Refrigerators',
                        'Washing Machines',
                        'Air-Conditioners',
                    ],
                ],
                'ar' => [
                    'name' => 'الأجهزة المنزلية الكبيرة',
                    'meta_title' => 'الأجهزة المنزلية الكبيرة',
                    'meta_description' => 'ثلاجات · غسالات · مكيفات هواء',
                    'units' => ['وحدة', 'قطعة', 'صندوق'],
                    'subcategories' => [
                        'ثلاجات',
                        'غسالات',
                        'مكيفات هواء',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Home & Furniture',
                    'slug' => 'home-furniture',
                    'order_level' => 9,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Home & Furniture',
                    'meta_description' => 'Furniture · Décor · Kitchenware · Bedding · Lighting',
                    'units' => ['piece', 'set', 'box'],
                    'subcategories' => [
                        'Furniture',
                        'Décor',
                        'Kitchenware',
                        'Bedding',
                        'Lighting',
                    ],
                ],
                'ar' => [
                    'name' => 'المنزل والأثاث',
                    'meta_title' => 'المنزل والأثاث',
                    'meta_description' => 'أثاث · ديكور · أدوات مطبخ · مفروشات · إضاءة',
                    'units' => ['قطعة', 'طقم', 'صندوق'],
                    'subcategories' => [
                        'أثاث',
                        'ديكور',
                        'أدوات مطبخ',
                        'مفروشات',
                        'إضاءة',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Home Improvement & DIY',
                    'slug' => 'home-improvement-diy',
                    'order_level' => 10,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Home Improvement & DIY',
                    'meta_description' => 'Power Tools · Paint · Plumbing · Electrical',
                    'units' => ['piece', 'set', 'kg', 'L', 'roll', 'm'],
                    'subcategories' => [
                        'Power Tools',
                        'Paint',
                        'Plumbing',
                        'Electrical',
                    ],
                ],
                'ar' => [
                    'name' => 'التحسينات المنزلية والأدوات',
                    'meta_title' => 'التحسينات المنزلية والأدوات',
                    'meta_description' => 'أدوات كهربائية · دهانات · سباكة · كهربائيات',
                    'units' => ['قطعة', 'طقم', 'كجم', 'لتر', 'لفة', 'متر'],
                    'subcategories' => [
                        'أدوات كهربائية',
                        'دهانات',
                        'سباكة',
                        'كهربائيات',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Building & Construction',
                    'slug' => 'building-construction',
                    'order_level' => 11,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Building & Construction',
                    'meta_description' => 'Cement · Steel · Wood · Insulation',
                    'units' => ['ton', 'kg', 'bag', 'piece', 'm'],
                    'subcategories' => [
                        'Cement',
                        'Steel',
                        'Wood',
                        'Insulation',
                    ],
                ],
                'ar' => [
                    'name' => 'مواد البناء والإنشاء',
                    'meta_title' => 'مواد البناء والإنشاء',
                    'meta_description' => 'أسمنت · حديد · أخشاب · عوازل',
                    'units' => ['طن', 'كجم', 'كيس', 'قطعة', 'متر'],
                    'subcategories' => [
                        'أسمنت',
                        'حديد',
                        'أخشاب',
                        'عوازل',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Industrial & Scientific',
                    'slug' => 'industrial-scientific',
                    'order_level' => 12,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Industrial & Scientific',
                    'meta_description' => 'Lab Equipment · Safety PPE · Instruments',
                    'units' => ['piece', 'unit', 'set', 'kg'],
                    'subcategories' => [
                        'Lab Equipment',
                        'Safety PPE',
                        'Instruments',
                    ],
                ],
                'ar' => [
                    'name' => 'الصناعي والعلمي',
                    'meta_title' => 'الصناعي والعلمي',
                    'meta_description' => 'معدات مختبر · معدات سلامة · أجهزة قياس',
                    'units' => ['قطعة', 'وحدة', 'طقم', 'كجم'],
                    'subcategories' => [
                        'معدات مختبر',
                        'معدات سلامة',
                        'أجهزة قياس',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Automotive',
                    'slug' => 'automotive',
                    'order_level' => 13,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Automotive',
                    'meta_description' => 'Spare Parts · Tires · Oils & Fluids · Car Care',
                    'units' => ['piece', 'set', 'L', 'bottle', 'kg'],
                    'subcategories' => [
                        'Spare Parts',
                        'Tires',
                        'Oils & Fluids',
                        'Car Care',
                    ],
                ],
                'ar' => [
                    'name' => 'السيارات وقطع الغيار',
                    'meta_title' => 'السيارات وقطع الغيار',
                    'meta_description' => 'قطع غيار · إطارات · زيوت وموائع · العناية بالسيارة',
                    'units' => ['قطعة', 'طقم', 'لتر', 'زجاجة', 'كجم'],
                    'subcategories' => [
                        'قطع غيار',
                        'إطارات',
                        'زيوت وموائع',
                        'العناية بالسيارة',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Pet Supplies',
                    'slug' => 'pet-supplies',
                    'order_level' => 14,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Pet Supplies',
                    'meta_description' => 'Pet Food · Accessories · Grooming · Healthcare',
                    'units' => ['kg', 'g', 'piece', 'pack', 'L'],
                    'subcategories' => [
                        'Pet Food',
                        'Accessories',
                        'Grooming',
                        'Healthcare',
                    ],
                ],
                'ar' => [
                    'name' => 'مستلزمات الحيوانات الأليفة',
                    'meta_title' => 'مستلزمات الحيوانات الأليفة',
                    'meta_description' => 'طعام حيوانات · إكسسوارات · عناية وتنظيف · صحة',
                    'units' => ['كجم', 'جم', 'قطعة', 'عبوة', 'لتر'],
                    'subcategories' => [
                        'طعام حيوانات',
                        'إكسسوارات',
                        'عناية وتنظيف',
                        'صحة',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Babies, Kids & Toys',
                    'slug' => 'babies-kids-toys',
                    'order_level' => 15,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Babies, Kids & Toys',
                    'meta_description' => 'Diapers · Baby Care · Toys & Games · School Supplies',
                    'units' => ['piece', 'pack', 'box', 'set'],
                    'subcategories' => [
                        'Diapers',
                        'Baby Care',
                        'Toys & Games',
                        'School Supplies',
                    ],
                ],
                'ar' => [
                    'name' => 'مستلزمات الأطفال والألعاب',
                    'meta_title' => 'مستلزمات الأطفال والألعاب',
                    'meta_description' => 'حفاضات · عناية بالرضع · ألعاب · مستلزمات مدرسية',
                    'units' => ['قطعة', 'عبوة', 'صندوق', 'طقم'],
                    'subcategories' => [
                        'حفاضات',
                        'عناية بالرضع',
                        'ألعاب',
                        'مستلزمات مدرسية',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Books & Media',
                    'slug' => 'books-media',
                    'order_level' => 16,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Books & Media',
                    'meta_description' => 'Printed Books · e-Books Codes · Music & Movies · Instruments',
                    'units' => ['piece', 'code', 'set'],
                    'subcategories' => [
                        'Printed Books',
                        'e-Books Codes',
                        'Music & Movies',
                        'Instruments',
                    ],
                ],
                'ar' => [
                    'name' => 'الكتب والوسائط',
                    'meta_title' => 'الكتب والوسائط',
                    'meta_description' => 'كتب مطبوعة · أكواد كتب إلكترونية · موسيقى وأفلام · أدوات موسيقية',
                    'units' => ['قطعة', 'كود', 'طقم'],
                    'subcategories' => [
                        'كتب مطبوعة',
                        'أكواد كتب إلكترونية',
                        'موسيقى وأفلام',
                        'أدوات موسيقية',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Stationery & Office',
                    'slug' => 'stationery-office',
                    'order_level' => 17,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Stationery & Office',
                    'meta_description' => 'Writing Instruments · Paper · Office Electronics',
                    'units' => ['piece', 'pack', 'box', 'ream'],
                    'subcategories' => [
                        'Writing Instruments',
                        'Paper',
                        'Office Electronics',
                    ],
                ],
                'ar' => [
                    'name' => 'القرطاسية والمكتب',
                    'meta_title' => 'القرطاسية والمكتب',
                    'meta_description' => 'أدوات كتابة · ورق · إلكترونيات مكتب',
                    'units' => ['قطعة', 'عبوة', 'صندوق', 'رزمة'],
                    'subcategories' => [
                        'أدوات كتابة',
                        'ورق',
                        'إلكترونيات مكتب',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Agri-supplies & Gardening',
                    'slug' => 'agri-supplies-gardening',
                    'order_level' => 18,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Agri-supplies & Gardening',
                    'meta_description' => 'Seeds · Fertilizers · Pesticides · Farm Tools · Live Plants',
                    'units' => ['kg', 'g', 'L', 'piece', 'bag'],
                    'subcategories' => [
                        'Seeds',
                        'Fertilizers',
                        'Pesticides',
                        'Farm Tools',
                        'Live Plants',
                    ],
                ],
                'ar' => [
                    'name' => 'الزراعة والحدائق',
                    'meta_title' => 'الزراعة والحدائق',
                    'meta_description' => 'بذور · أسمدة · مبيدات · أدوات زراعية · نباتات',
                    'units' => ['كجم', 'جم', 'لتر', 'قطعة', 'كيس'],
                    'subcategories' => [
                        'بذور',
                        'أسمدة',
                        'مبيدات',
                        'أدوات زراعية',
                        'نباتات',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Travel & Experiences',
                    'slug' => 'travel-experiences',
                    'order_level' => 19,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Travel & Experiences',
                    'meta_description' => 'Flights · Hotels · Events · Theme Parks · Tours',
                    'units' => ['ticket', 'voucher', 'code'],
                    'subcategories' => [
                        'Flights',
                        'Hotels',
                        'Events',
                        'Theme Parks',
                        'Tours',
                    ],
                ],
                'ar' => [
                    'name' => 'السفر والتجارب',
                    'meta_title' => 'السفر والتجارب',
                    'meta_description' => 'رحلات طيران · فنادق · فعاليات · مدن ترفيه · جولات سياحية',
                    'units' => ['تذكرة', 'قسيمة', 'كود'],
                    'subcategories' => [
                        'رحلات طيران',
                        'فنادق',
                        'فعاليات',
                        'مدن ترفيه',
                        'جولات سياحية',
                    ],
                ],
            ],
            [
                'en' => [
                    'name' => 'Digital & Services',
                    'slug' => 'digital-services',
                    'order_level' => 20,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                    'meta_title' => 'Digital & Services',
                    'meta_description' => 'Mobile Top-ups · Gift Cards · Software Keys · Subscriptions',
                    'units' => ['code', 'subscription', 'month', 'year'],
                    'subcategories' => [
                        'Mobile Top-ups',
                        'Gift Cards',
                        'Software Keys',
                        'Subscriptions',
                    ],
                ],
                'ar' => [
                    'name' => 'الخدمات الرقمية',
                    'meta_title' => 'الخدمات الرقمية',
                    'meta_description' => 'شحن رصيد · بطاقات هدايا · مفاتيح برامج · اشتراكات',
                    'units' => ['كود', 'اشتراك', 'شهر', 'سنة'],
                    'subcategories' => [
                        'شحن رصيد',
                        'بطاقات هدايا',
                        'مفاتيح برامج',
                        'اشتراكات',
                    ],
                ],
            ],
        ];

        foreach ($categories as $categoryData) {
            // Create parent category (English)
            $parentCategory = Category::create([
                'name' => $categoryData['en']['name'],
                'slug' => $categoryData['en']['slug'],
                'order_level' => $categoryData['en']['order_level'],
                'banner' => $categoryData['en']['banner'],
                'icon' => $categoryData['en']['icon'],
                'featured' => $categoryData['en']['featured'],
                'meta_title' => $categoryData['en']['meta_title'],
                'meta_description' => $categoryData['en']['meta_description'],
                'unit' => $categoryData['en']['units'],
            ]);

            // Create Arabic translation for parent
            $parentCategory->translations()->create([
                'locale' => 'ar',
                'name' => $categoryData['ar']['name'],
                'meta_title' => $categoryData['ar']['meta_title'],
                'meta_description' => $categoryData['ar']['meta_description'],
            ]);

            // Create subcategories (English and Arabic)
            foreach ($categoryData['en']['subcategories'] as $index => $subNameEn) {
                $subCategory = Category::create([
                    'name' => $subNameEn,
                    'slug' => Str::slug($subNameEn),
                    'order_level' => $categoryData['en']['order_level'] + 1,
                    'parent_id' => $parentCategory->id,
                    'unit' => $categoryData['en']['units'],
                    'meta_title' => $subNameEn,
                    'meta_description' => $subNameEn,
                    'banner' => null,
                    'icon' => null,
                    'featured' => false,
                ]);

                // Arabic translation for subcategory
                $subCategory->translations()->create([
                    'locale' => 'ar',
                    'name' => $categoryData['ar']['subcategories'][$index],
                    'meta_title' => $categoryData['ar']['subcategories'][$index],
                    'meta_description' => $categoryData['ar']['subcategories'][$index],
                ]);
            }
        }
    }
}
