<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Shipping Label - {{ $order->tracking }}</title>
    <style>
        @page { margin: 15px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .label-container { border: 2px solid #000; padding: 15px; page-break-inside: avoid; }
        .header { text-align: center; margin-bottom: 15px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin: 15px 0; }
        .barcode-section { text-align: center; margin: 20px 0; padding: 10px; background: #f5f5f5; }
        .product-table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        .product-table th { background: #f8f9fa; text-align: left; padding: 8px; border: 1px solid #dee2e6; }
        .product-table td { padding: 8px; border: 1px solid #dee2e6; }
        .summary-box { padding: 15px; border: 1px solid #dee2e6; margin-top: 15px; }
        .warning { color: #dc3545; font-weight: bold; font-size: 14px; }
    </style>
</head>
<body>
    <div class="label-container">
        <div class="header">
            <h2 style="margin: 0;">SHIPPING LABEL</h2>
        </div>

        <div class="grid">
            <div>
                <h3 style="margin-top: 0;">Shipper Information</h3>
                @if($store)
                <p style="margin: 2px 0;">
                    {{ $store->name ?? '' }}<br>
                    {{ $store->address ?? '' }}<br>
                    Phone: {{ $store->phone_number ?? '' }}
                </p>
                @endif
            </div>

            <div>
                <h3 style="margin-top: 0;">Recipient Information</h3>
                <p style="margin: 2px 0;">
                    {{ $order->shipping_first_name }} {{ $order->shipping_last_name }}<br>
                    {{ $order->shipping_address_line1 }}<br>
                    @if($order->shipping_address_line2)
                        {{ $order->shipping_address_line2 }}<br>
                    @endif
                    {{ $order->shipping_city }}, {{ $order->shipping_state }} {{ $order->shipping_postal_code }}<br>
                    {{ $order->shipping_country }}
                </p>
            </div>
        </div>

        <div class="barcode-section">
            {!! $barcode !!}
            <div style="margin-top: 10px; font-weight: bold;">
                Tracking #: {{ $order->tracking }}<br>
                Order Date: {{ $order->created_at->format('M d, Y') }}
            </div>
        </div>

        <h3>Product Details</h3>
        <table class="product-table">
            <thead>
                <tr>
                    <th>Product ID</th>
                    <th>Quantity</th>
                    <th>Attributes</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach(json_decode($order->product_details, true) as $item)
                <tr>
                    <td>#{{ $item['product_id'] }}</td>
                    <td>{{ $item['quantity'] }}</td>
                    <td>
                        @foreach($item['attributes'] as $attribute)
                            @if(!empty($attribute['attribute']))
                            <div>{{ $attribute['attribute'] }}: 
                                <strong>{{ $attribute['value'] ?? 'N/A' }}</strong>
                                @if($attribute['price'] ?? false)
                                    (SAR {{ number_format($attribute['price'], 2) }})
                                @endif
                            </div>
                            @endif
                        @endforeach
                    </td>
                    <td>
                        SAR {{ number_format(array_sum(array_column($item['attributes'], 'price')) * $item['quantity'], 2) }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="summary-box">
            <div style="display: flex; justify-content: space-between;">
                <div>
                    <strong>Total Items:</strong> {{ count(json_decode($order->product_details, true)) }}<br>
                    <strong>Total Quantity:</strong> {{ array_sum(array_column(json_decode($order->product_details, true), 'quantity')) }}
                </div>
                <div>
                    <strong>Shipping Cost:</strong> SAR {{ number_format($order->shipping_cost, 2) }}<br>
                    <strong>Grand Total:</strong> SAR {{ number_format($order->grand_total, 2) }}
                </div>
            </div>
        </div>

        <div style="margin-top: 15px; font-size: 10px; color: #6c757d; text-align: center;">
            Generated by {{ $store->shop_name ?? 'Our Store' }} on {{ now()->format('M d, Y H:i') }}<br>
            {{ config('app.name') }} • {{ config('app.url') }}
        </div>
    </div>
</body>
</html>